import Head from 'next/head';
import Image from 'next/image';
import Card from '../Components/Card/Card';
import DarkFooter from '../Components/DarkFooter/DarkFooter';
import Footer from '../Components/Footer/Footer';
import GoogleLine from '../Components/GoogleLine/GoogleLine';
import Header from '../Components/Header/Header';
import Main from '../Components/Main/Main';
import StepCard from '../Components/StepCard/StepCard';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ratepunk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header />
      <main className={styles.main}>
        <Main>
          <Card
            title='refer friends and get rewards'
            text="Refer your friends to us and earn hotel booking vouchers. We'll give you 1 coin for each friend that installs our extension. Minimum cash-out at 20 coins."
          />
          <StepCard />
        </Main>
      </main>

      <DarkFooter>
        <GoogleLine />
      </DarkFooter>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
